//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevAssessment.EntityFramework.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int IDNumber { get; set; }
        public string FullName { get; set; }
        public string Surname { get; set; }
        public int GenderID { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int ContactPreference { get; set; }
        public string PhotoPath { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual ContactPreference ContactPreference1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
